workflows:
  flutter-monorepo-build:
    name: Flutter Ditonton Build
    instance_type: mac_mini_m1
    
    environment:
      # API Key untuk TMDB (dikonfigurasi di CodeMagic UI)
      groups:
        - tmdb_api

    scripts:
      # --- Setup & Dependencies ---
      - name: Install Flutter and Melos
        script: |
          flutter channel stable
          flutter upgrade
          flutter pub global activate melos

      - name: Verify Melos Installation
        script: |
          melos --version  # Memastikan bahwa Melos terinstal dengan benar

      - name: Get dependencies and link packages
        script: |
          # Melos akan menjalankan 'flutter pub get' di semua modul
          melos run pub-get

      # --- Unit & Widget Tests ---
      - name: Run tests on all packages
        script: |
          # Melos akan menjalankan 'flutter test' di semua modul
          melos run test

      # --- Build Android AppBundle ---
      - name: Build Android APK
        script: |
          # Gunakan 'flutter build apk' untuk membuat APK release
          flutter build apk --release --dart-define=API_KEY=$CM_API_KEY

      # --- Build iOS App ---
      - name: Build iOS IPA
        script: |
          # Gunakan 'flutter build ipa' untuk membuat IPA release
          flutter build ipa --release --dart-define=API_KEY=$CM_API_KEY
          
    # Lokasi file hasil build
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa

    # Proses publishing (opsional)
    publishing:
      email:
        recipients:
          - azizkandias11@gmail.com
    triggering:
      events:
        - pull_request
        - push
    scripts:
      - name: Melos Bootstrap
         script: |
           dart pub global activate melos
           melos bootstrap 
            - name: Run Analyze
         script: melos run analyze

      - name: Run Format
         script: melos run format

      - name: Run Tests
         script: melos run test
