name: ditonton_expert
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  core:
    path: packages/core
  shared_ui:
    path: packages/shared_ui
  feature_setting:
    path: packages/feature_setting
  feature_about: 
    path: packages/feature_about
  feature_movie:
    path: packages/feature_movie
  feature_tv_series:
    path: packages/feature_tv_series
  feature_search:
    path: packages/feature_search
  feature_watchlist:
    path: packages/feature_watchlist
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  get_it: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  melos: ^7.1.0


flutter:
  assets:
    - packages/feature_about/assets/
    - assets/
  uses-material-design: true

melos:
  scripts:
    pub-get:
      run: flutter pub get
      description: Run `flutter pub get` in all packages
    analyze:
      run: melos exec -- "flutter analyze"
      description: Run `flutter analyze` in all packages
    format:
      run: melos exec -- "flutter format . --set-exit-if-changed"
      description: Run `flutter format .` in all packages
    test:
      # Only run the test command when the package has a test directory
      run: melos exec --dir-exists=test -- "flutter test"
      description: Run `flutter test` in all packages

workspace:
  - packages/core
  - packages/shared_ui
  - packages/feature_setting
  - packages/feature_about
  - packages/feature_movie
  - packages/feature_tv_series
  - packages/feature_search
  - packages/feature_watchlist

