// Mocks generated by Mockito 5.4.6 from annotations
// in feature_watchlist/test/presentation/pages/watchlist_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:feature_movie/domain/usecases/get_watchlist_movies.dart' as _i2;
import 'package:feature_tv_series/domain/usecases/get_watchlist_tv_series.dart'
    as _i3;
import 'package:feature_watchlist/presentation/cubit/watchlist_cubit.dart'
    as _i5;
import 'package:feature_watchlist/presentation/cubit/watchlist_state.dart'
    as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWatchlistMovies_0 extends _i1.SmartFake
    implements _i2.GetWatchlistMovies {
  _FakeGetWatchlistMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTvSeriesUseCase_1 extends _i1.SmartFake
    implements _i3.GetWatchlistTvSeriesUseCase {
  _FakeGetWatchlistTvSeriesUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistState_2 extends _i1.SmartFake
    implements _i4.WatchlistState {
  _FakeWatchlistState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchlistCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistCubit extends _i1.Mock implements _i5.WatchlistCubit {
  MockWatchlistCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistMovies),
            returnValue: _FakeGetWatchlistMovies_0(
              this,
              Invocation.getter(#getWatchlistMovies),
            ),
          )
          as _i2.GetWatchlistMovies);

  @override
  _i3.GetWatchlistTvSeriesUseCase get getWatchlistTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTvSeries),
            returnValue: _FakeGetWatchlistTvSeriesUseCase_1(
              this,
              Invocation.getter(#getWatchlistTvSeries),
            ),
          )
          as _i3.GetWatchlistTvSeriesUseCase);

  @override
  _i4.WatchlistState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistState_2(this, Invocation.getter(#state)),
          )
          as _i4.WatchlistState);

  @override
  _i6.Stream<_i4.WatchlistState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.WatchlistState>.empty(),
          )
          as _i6.Stream<_i4.WatchlistState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchlist, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i4.WatchlistState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i4.WatchlistState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
