// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOn-l0BDRKpg904mbhERY-U0BBtvNz1M',
    appId: '1:318008520102:web:d83f8b6133fae01a03b367',
    messagingSenderId: '318008520102',
    projectId: 'ditonton-expert-9e3c0',
    authDomain: 'ditonton-expert-9e3c0.firebaseapp.com',
    storageBucket: 'ditonton-expert-9e3c0.firebasestorage.app',
    measurementId: 'G-5MQL6W11HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHMEUMeRYJpOKupdfBWZv4yyxqe_o5gk',
    appId: '1:318008520102:android:33df4809f27340b503b367',
    messagingSenderId: '318008520102',
    projectId: 'ditonton-expert-9e3c0',
    storageBucket: 'ditonton-expert-9e3c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCse0b6l_d_VZA0egMngX1GLJZCUIEePEA',
    appId: '1:318008520102:ios:3cc4f51a1f02813903b367',
    messagingSenderId: '318008520102',
    projectId: 'ditonton-expert-9e3c0',
    storageBucket: 'ditonton-expert-9e3c0.firebasestorage.app',
    iosBundleId: 'com.zeekands.ditontonExpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCse0b6l_d_VZA0egMngX1GLJZCUIEePEA',
    appId: '1:318008520102:ios:3cc4f51a1f02813903b367',
    messagingSenderId: '318008520102',
    projectId: 'ditonton-expert-9e3c0',
    storageBucket: 'ditonton-expert-9e3c0.firebasestorage.app',
    iosBundleId: 'com.zeekands.ditontonExpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEOn-l0BDRKpg904mbhERY-U0BBtvNz1M',
    appId: '1:318008520102:web:d7096e09f7f07b9203b367',
    messagingSenderId: '318008520102',
    projectId: 'ditonton-expert-9e3c0',
    authDomain: 'ditonton-expert-9e3c0.firebaseapp.com',
    storageBucket: 'ditonton-expert-9e3c0.firebasestorage.app',
    measurementId: 'G-4SM8P9K2W4',
  );
}
