// Mocks generated by Mockito 5.4.6 from annotations
// in feature_search/test/presentation/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/common/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:feature_movie/domain/entities/movie.dart' as _i6;
import 'package:feature_movie/domain/usecases/search_movie.dart' as _i3;
import 'package:feature_tv_series/domain/entities/tv_series.dart' as _i8;
import 'package:feature_tv_series/domain/usecases/search_tv_series.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchMovieUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovieUseCase extends _i1.Mock
    implements _i3.SearchMovieUseCase {
  MockSearchMovieUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> execute(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
}

/// A class which mocks [SearchTvSeriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeriesUseCase extends _i1.Mock
    implements _i7.SearchTvSeriesUseCase {
  MockSearchTvSeriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvSeries>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.TvSeries>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvSeries>>>);
}
