// Mocks generated by Mockito 5.4.6 from annotations
// in feature_search/test/presentation/pages/search_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:feature_movie/domain/usecases/search_movie.dart' as _i2;
import 'package:feature_search/presentation/bloc/search_bloc.dart' as _i5;
import 'package:feature_search/presentation/bloc/search_event.dart' as _i7;
import 'package:feature_search/presentation/bloc/search_state.dart' as _i4;
import 'package:feature_tv_series/domain/usecases/search_tv_series.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchMovieUseCase_0 extends _i1.SmartFake
    implements _i2.SearchMovieUseCase {
  _FakeSearchMovieUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTvSeriesUseCase_1 extends _i1.SmartFake
    implements _i3.SearchTvSeriesUseCase {
  _FakeSearchTvSeriesUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchState_2 extends _i1.SmartFake implements _i4.SearchState {
  _FakeSearchState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchBloc extends _i1.Mock implements _i5.SearchBloc {
  MockSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchMovieUseCase get searchMovies =>
      (super.noSuchMethod(
            Invocation.getter(#searchMovies),
            returnValue: _FakeSearchMovieUseCase_0(
              this,
              Invocation.getter(#searchMovies),
            ),
          )
          as _i2.SearchMovieUseCase);

  @override
  _i3.SearchTvSeriesUseCase get searchTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#searchTvSeries),
            returnValue: _FakeSearchTvSeriesUseCase_1(
              this,
              Invocation.getter(#searchTvSeries),
            ),
          )
          as _i3.SearchTvSeriesUseCase);

  @override
  _i4.SearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSearchState_2(this, Invocation.getter(#state)),
          )
          as _i4.SearchState);

  @override
  _i6.Stream<_i4.SearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.SearchState>.empty(),
          )
          as _i6.Stream<_i4.SearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.SearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.SearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.SearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.SearchEvent>(
    _i8.EventHandler<E, _i4.SearchState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i7.SearchEvent, _i4.SearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i4.SearchState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
