name: feature_movie
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  shared_ui:
    path: ../shared_ui
  cached_network_image: ^3.4.0
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^3.2.0     
  mockito: ^5.5.0 
  bloc_test: ^10.0.0

flutter:
resolution: workspace